name: Continuous Integration

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  continuous-integration:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Run install
        run: npm install

      - name: Run lint
        run: npm run lint

      - name: Run test
        run: |
          npx playwright install
          npm run test
